// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3scqT6_QiICpBqE5w0zb2UfvNGu1dLvc',
    appId: '1:144435307724:web:ad0014500204bfe59d8e69',
    messagingSenderId: '144435307724',
    projectId: 'mama-bus-koi-e4bb9',
    authDomain: 'mama-bus-koi-e4bb9.firebaseapp.com',
    storageBucket: 'mama-bus-koi-e4bb9.firebasestorage.app',
    measurementId: 'G-NJG6LN0N56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVBXErTymQ-a4SU1KwJwy5cC_HC_qfkVI',
    appId: '1:144435307724:android:78f3efed623083239d8e69',
    messagingSenderId: '144435307724',
    projectId: 'mama-bus-koi-e4bb9',
    databaseURL:
        'https://mama-bus-koi-e4bb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mama-bus-koi-e4bb9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtbgI-XET_CYnpxwcDogzMi8KlZfCNIU',
    appId: '1:144435307724:ios:0474d808021517129d8e69',
    messagingSenderId: '144435307724',
    projectId: 'mama-bus-koi-e4bb9',
    storageBucket: 'mama-bus-koi-e4bb9.firebasestorage.app',
    iosBundleId: 'com.example.buskoi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtbgI-XET_CYnpxwcDogzMi8KlZfCNIU',
    appId: '1:144435307724:ios:0474d808021517129d8e69',
    messagingSenderId: '144435307724',
    projectId: 'mama-bus-koi-e4bb9',
    storageBucket: 'mama-bus-koi-e4bb9.firebasestorage.app',
    iosBundleId: 'com.example.buskoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3scqT6_QiICpBqE5w0zb2UfvNGu1dLvc',
    appId: '1:144435307724:web:2d8da2ca5d8c07119d8e69',
    messagingSenderId: '144435307724',
    projectId: 'mama-bus-koi-e4bb9',
    authDomain: 'mama-bus-koi-e4bb9.firebaseapp.com',
    storageBucket: 'mama-bus-koi-e4bb9.firebasestorage.app',
    measurementId: 'G-RK2PM6WXYS',
  );
}
